---
# - name: Parse lspci output for AMD and NVIDIA devices and get detailed info
- hosts: "vm_server"
  become: true # попытаться выполнить под указанным пользователем
  become_method: su
  become_user: root
  tasks:
    - name: Extract AMD PCI IDs
      ansible.builtin.shell: "lspci | grep NVIDIA"
      register: lspci_output_nvidia

    - name: Extract NVIDIA PCI IDs
      ansible.builtin.shell: "lspci | grep AMD"
      register: lspci_output_amd

    - name: Display AMD IDs as a string
      ansible.builtin.debug:
        var: lspci_output_amd

    - name: Display NVIDIA IDs as a string
      ansible.builtin.debug:
        var: lspci_output_nvidia

    - name: Extract NVIDIA PCI IDs
      ansible.builtin.shell: "lspci -n -s {{ item.split(' ')[0] }} | awk '{print $3}'"
      with_items: "{{ lspci_output_nvidia.stdout_lines }}"  # Проходим по каждой строке вывода команды lspci
      register: lspci_output_asbolute_nvidia
      tags:
        - parsing

    #- name: Extract AMD PCI IDs
    #  ansible.builtin.shell: "lspci -n -s {{ item.split(' ')[0] }} | awk '{print $3}'"
    #  with_items: "{{ lspci_output_amd.stdout_lines }}"  # Проходим по каждой строке вывода команды lspci
    #  register: lspci_output_asbolute_amd
    #  tags:
    #    - parsing

    - name: Display NVIDIA IDs as a list
      ansible.builtin.debug:
        var: lspci_output_asbolute_nvidia

    #- name: Display AMD IDs as a list
    #  ansible.builtin.debug:
    #    var: lspci_output_asbolute_amd

    #- name: Join AMD PCI IDs
    #  ansible.builtin.set_fact:
    #    myvar: "{{ lspci_output_asbolute_amd.results | join(',') }}"

    - name: Join NVIDIA PCI IDs
      ansible.builtin.set_fact:
        lspci_output_asbolute_nvidia_as_str: "{{ lspci_output_asbolute_nvidia_as_str | default() + ',' + item.stdout_lines[0] }}"
      with_items:  "{{ lspci_output_asbolute_nvidia.results }}"

    - name: Trim NVIDIA PCI IDs - 2
      ansible.builtin.set_fact:
        lspci_output_asbolute_nvidia_as_str: "{{ lspci_output_asbolute_nvidia_as_str | trim(',') }}"

    - name: Display NVIDIA IDs as a string
      ansible.builtin.debug:
        var: lspci_output_asbolute_nvidia_as_str

    #- name: Append NVIDIA IDs to /etc/modprobe.d/vfio.conf
    #  ansible.builtin.lineinfile:
    #    path: /etc/modprobe.d/vfio.conf
    #    line: "options vfio-pci ids={{ nvidia_ids_string }} disable_vga=1"
    #    create: yes
    #    insertafter: EOF

    - name: Append NVIDIA to /etc/modprobe.d/vfio.conf
      ansible.builtin.lineinfile:
        path: /etc/modprobe.d/vfio.conf
        line: "options vfio-pci ids={{ lspci_output_asbolute_nvidia_as_strчц }} disable_vga=1 # NVIDIA"
        create: yes
        insertafter: EOF
