# Настройка VGPU на хосте

--- # Указывает на начало
- hosts: "vm_server"
  become: true # попытаться выполнить под указанным пользователем
  become_method: su
  become_user: root
  tasks:
    - name: "Enable grouping by IOMMU in GRUB"
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: '^.*GRUB_CMDLINE_LINUX_DEFAULT='
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet intel_iommu=on amd_iommu=on iommu=pt"'

    - name: "Update GRUB"
      ansible.builtin.command: update-grub

    - name: "Activate IOMMU unsafe_interrupts in modprobe.d"
      ansible.builtin.lineinfile:
        path: /etc/modprobe.d/iommu_unsafe_interrupts.conf
        regexp: '^options'
        line: 'options vfio_iommu_type1 allow_unsafe_interrupts=1'
        create: true

    - name: "Activate KVM ignore_msrs in modprobe.d"
      ansible.builtin.lineinfile:
        path: /etc/modprobe.d/kvm.conf
        regexp: '^options'
        line: 'options kvm ignore_msrs=1'
        create: true

    - name: "Add vfio settings to modules"
      ansible.builtin.blockinfile:
        path: /etc/modules-load.d/vfio.conf
        create: true
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        insertafter: EOF
        block: |
          vfio
          vfio_iommu_type1
          vfio_pci
          vfio_virqfd

    - name: "Restrict using GPU drivers in host"
      ansible.builtin.blockinfile:
        path: /etc/modprobe.d/blacklist.conf
        create: true
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        insertafter: EOF
        block: |
          # AMD GPUs
          blacklist amdgpu
          blacklist radeon
          # NVIDIA GPUs
          blacklist nouveau
          blacklist nvidia*
          # Intel GPUs
          blacklist i915

    # Will work after reboot!
    - name: "Search installed NVIDIA GPU PCI id"
      ansible.builtin.command: 'lspci | grep NVIDIA |  awk "{print $1}"'
      register: nvidia_out

    - name: "Search installed AMD GPU PCI id"
      ansible.builtin.command: 'lspci | grep AMD |  awk "{print $1}"'
      register: amd_out

    #    - command:
    #        -  # print relative id ex: 01:00.0
    #        - lspci -n -s 01:00.0 | awk '{print $3}' # ex: 10de:2d04

    # for g in $(find /sys/kernel/iommu_groups/* -maxdepth 0 -type d | sort -V); do
    #    echo "IOMMU Group ${g##*/}:"
    #    for d in $g/devices/*; do
    #        echo -e "\t$(lspci -nns ${d##*/})"
    #    done;
    #done;

    #- name: "Activate vfio-pci for GPU"
    #  ansible.builtin.apt:
    #    - command:
    #        - echo options vfio-pci ids=10de:1b81,10de:10f0 disable_vga=1 >> /etc/modprobe.d/vfio.conf
    #- name: "Activate settings"
    #  ansible.builtin.apt:
    #    - command:
    #        - update-initramfs -u -k all
... # Указывает на конец